site_name: 'Selena Wang, PhD'
repo_name: 'selenawangcv'

extra_css:
  - styles/extra.css

nav:
  - Home: home.md
  - Research: research.md
  - Publications: publications.md
  - Teaching: teaching.md
  - Software: software.md            

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      schema: default
      primary: 'indigo'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - content.tabs.link    

markdown_extensions:
  - def_list
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html  
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
